name: Backport Merged Pull Requests

on:
  pull_request_target:
    types: [closed]

jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest

    permissions:
      contents: write # so it can comment
      pull-requests: write # so it can create pull requests

    # Only run if the pull request was merged and not by a bot
    if: ${{ github.event.pull_request.merged == true && github.actor != 'github-actions[bot]' }}
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create Backport Pull Request
        uses: korthout/backport-action@v3
        with:
          cherry_picking: auto
          copy_labels_pattern: '^(?!cla-signed$).*' # copy all labels other than the cla-signed label
          label_pattern: 'backport-to-(support\/\d+\.\d+)' # regex to match labels like backport-to-support/2.14
          conflict_resolution: 'draft_commit_conflicts' # create a draft PR if there are conflicts
